/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import static Inicio.IniciarConeccion.connection;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class Cliente extends javax.swing.JInternalFrame {
public int Ingreso;
public int Costo;
public int ganancia;
public int paquetes;
public LinkedList<String> lista;
String html;
    public Cliente() {
        initComponents();
        this.html="";
        lista=new LinkedList();
        llenarCombo();
        
        this.Ingreso=0;
        this.Costo=0;
        this.ganancia=0;
        this.paquetes=0;
    }
public void llenarCombo(){
combo.removeAllItems();
combo.addItem("Todos");
        try {
         PreparedStatement declaracion =connection.prepareStatement("SELECT cliente.cui FROM cliente ");
         
         ResultSet re=declaracion.executeQuery();
         while(re.next()){
         combo.addItem(Integer.toString(re.getInt("cui")));
         lista.add(Integer.toString(re.getInt("cui")));
         }
         
         
        } catch (SQLException ex) {
        
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cui", "P/Entregados", "Costo", "Ingreso", "Ganancia"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 180));

        jButton2.setText("HTML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(combo.getSelectedItem().toString().equals("Todos")){
      tabla.removeAll();
      
      LlenarTabla2();
      }else{
      tabla.removeAll();    
      LlenarTabla1();
      
      }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
public  String llenarHTML(){
    
      File file=new File("report.png");
      String scr=file.getAbsolutePath();
String HTML="<!DOCTYPE html>\n" +
"<html lang=\"en\">\n" +
"<head>\n" +
"    <meta charset=\"UTF-8\">\n" +
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
"    <title>Document</title>\n" +
"</head>\n" +
"<body>\n" +
"    <header>\n" +
"        <img  src=\""+scr+"\" alt=\"img\">\n" +
"    </header>\n" +
"     \n" +
        "<ul>\n" +
"        <div >\n" +
"            <table id=\"historial\" style=\"width: 50%\" >\n" +
"                    \n" +
"                <tr>\n" +
"                        <th><h2>CUI</h2></th>\n" +
"                        <th><h2>ENTREGADOS</h2></th>\n" +
"                        <th><h2>COSTO</h2></th> \n" +
"                        <th><h2>INGRESO</h2></th> \n" + 
"                        <th><h2>GANANCIA</h2></th> \n" +        
"               </tr >\n" +html+
"            </table>\n" +
"            </div>\n" +
"</ul>\n" +
        
" <style>\n" +
" body{\n" +
"     background-color: darkblue;\n" +
" }\n" +
" header{\n" +
"    background-color: white;\n" +
"\n" +
" }\n" +
" img{\n" +
"    height: 15%;\n" +
"    width: 15%;\n" +
"    padding-left: 43%;\n" +
"\n" +
" }\n" +
" th{\n" +
"background-color: white;\n" +
"margin: auto;\n" +
" }\n" +
" table{\n" +
"     background-color:steelblue;\n" +
"     margin: auto;\n" +
" }\n" +
"h4{\n" +
"text-align: center;\n" +
"\n" +
"}\n" +
"</style>   \n" +
"\n" +
""+
"</table>\n" +
"</body>\n" +
"</html>";

return HTML;
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Directori a=new Directori();
        
        File file=new File(a.directorio());
        if(file.exists()){
        JOptionPane.showMessageDialog(this,"Este archivo ya existe");
        }else{
           try {
               BufferedWriter bw;
               bw = new BufferedWriter(new FileWriter(file));
               bw.write( llenarHTML());
                bw.close();
           } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,"Error al guardar");
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void LlenarTabla1(){
    Costo=0;
    Ingreso=0;
    ganancia=0;
    paquetes=0;
    html="";       

        try {
     PreparedStatement Table;
            Table=connection.prepareStatement("SELECT ganancia.ganancia FROM ganancia WHERE cui=?" );
            Table.setInt(1,Integer.parseInt(combo.getSelectedItem().toString()));
            ResultSet I;       
            I=Table.executeQuery();
            while(I.next()){
            this.Ingreso+=I.getInt("ganancia");
            }
           Table=connection.prepareStatement("SELECT paquete.precio FROM paquete WHERE cui=? && (estado=? || estado=?)" );
            Table.setInt(1,Integer.parseInt(combo.getSelectedItem().toString()));
            Table.setString(2, "entregado");
            Table.setString(3,"destino");
            I=Table.executeQuery();
            while(I.next()){
            this.Costo+=I.getInt("precio");
            this.paquetes+=1;
            }
           
            this.ganancia=Ingreso-Costo;
            System.out.println(Costo+"a"+paquetes);
            String matris[][]=new String[1][5];
            matris[0][0]=combo.getSelectedItem().toString();
            matris[0][1]=Integer.toString(paquetes);
            matris[0][2]=Integer.toString(Costo);
            matris[0][3]=Integer.toString(Ingreso);
            matris[0][4]=Integer.toString(ganancia);
               html+="<tr>"
            + "<td>"+matris[0][0]+" </td> "
            + "<td>"+matris[0][1]+" </td> "
            + "<td>"+matris[0][2]+" </td> "
            + "<td>"+matris[0][3]+" </td> "
             + "<td>"+matris[0][4]+" </td> "
                       + "</tr>";
            
            tabla.setModel(new javax.swing.table.DefaultTableModel(
          matris,
          new String [] {
                "Cui", "P/Entregados", "Costo", "Ingreso", "Ganancia"
            }
        ));
     tabla.disable();
        } catch (SQLException ex) {
        System.out.println(ex.getMessage());
        }
         
    
}
public void LlenarTabla2(){
    String matris[][]=new String[lista.size()][5];
    
    PreparedStatement Table;
     ResultSet I;
   for(int i=0;i<lista.size();i++ ){
        Costo=0;
    Ingreso=0;
    ganancia=0;
    paquetes=0;
        try {
           
            Table=connection.prepareStatement("SELECT ganancia.ganancia FROM ganancia WHERE cui=?" );
            Table.setInt(1,Integer.parseInt(lista.get(i)));
           
            I=Table.executeQuery();
            while(I.next()){
            this.Ingreso+=I.getInt("ganancia");
            }
           Table=connection.prepareStatement("SELECT paquete.precio FROM paquete WHERE cui=? && (estado=? || estado=?)" );
            Table.setInt(1,Integer.parseInt(lista.get(i)));
            Table.setString(2, "entregado");
            Table.setString(3,"destino");
            I=Table.executeQuery();
            while(I.next()){
            this.Costo+=I.getInt("precio");
            this.paquetes+=1;
            }
           
            this.ganancia=Ingreso-Costo;
            
           
            matris[i][0]=lista.get(i);
            matris[i][1]=Integer.toString(paquetes);
            matris[i][2]=Integer.toString(Costo);
            matris[i][3]=Integer.toString(Ingreso);
            matris[i][4]=Integer.toString(ganancia);
               html+="<tr>"
            + "<td>"+matris[i][0]+" </td> "
            + "<td>"+matris[i][1]+" </td> "
            + "<td>"+matris[i][2]+" </td> "
            + "<td>"+matris[i][3]+" </td> "
             + "<td>"+matris[i][4]+" </td> "
                       + "</tr>";
        
    
        } catch (SQLException ex) {
        
        }
   }
          tabla.setModel(new javax.swing.table.DefaultTableModel(
          matris,
          new String [] {
                "Cui", "P/Entregados", "Costo", "Ingreso", "Ganancia"
            }
        ));
     tabla.disable();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
