/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import static Inicio.IniciarConeccion.connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static ExtraClasses.GenararPilas.COLARUTA;
import datechooser.model.multiple.Period;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.util.Calendar;
import javax.swing.JOptionPane;

public class Ganancias extends javax.swing.JInternalFrame {

public int Ingreso;
public int Costo=0;
String html;
public int ganancia=0;

    public Ganancias() {
        initComponents();
       llenarCombo();
        this.setLocation(50,50);
        this.Ingreso=0;
        this.Costo=0;
        this.ganancia=0;
 
      
    }
    public String Jfecha1(){
        String []tmp=Fecha1.getSelection().toString().split("");
        String tmp2="";
        for(int i=0; i<tmp.length; i++){
            if(tmp[i].equals("[") ||tmp[i].equals("]") ){
            }else{
            tmp2+=tmp[i];
            }
        }
    return tmp2;}
      public String Jfecha2(){
        String []tmp=Fecha2.getSelection().toString().split("");
        String tmp2="";
        for(int i=0; i<tmp.length; i++){
            if(tmp[i].equals("[") ||tmp[i].equals("]") ){
            }else{
            tmp2+=tmp[i];
            }
        }
    return tmp2;}
public void llenarCombo(){
combo.removeAllItems();
combo.addItem("Todos");
        try {
         PreparedStatement declaracion =connection.prepareStatement("SELECT ruta.direccion_rta, ruta.id_ruta FROM ruta WHERE estado=?" );
         declaracion.setString(1, "activo");
         ResultSet re=declaracion.executeQuery();
         while(re.next()){
         combo.addItem(re.getString("direccion_rta")+" "+"ID:"+re.getString("id_ruta"));
         }
         
         
        } catch (SQLException ex) {
        
        }

}

public String obtenerLetra(){
    String letra="0";
     try{
     String tmp=combo.getSelectedItem().toString();
     String [] vect=tmp.split("");
     String numbers="1234567890";
     String [] vect2=numbers.split("");
     
     for(int i=0; i<tmp.length();i++){
       
     for(int j=0;j<numbers.length();j++){
         
     if(vect[i].equals(vect2[j]))
     {
        letra+=vect[i]; 
     
     break;
     }
     }
     }
    }catch(NullPointerException e){
     
     }
    return letra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Fecha1 = new datechooser.beans.DateChooserCombo();
        Fecha2 = new datechooser.beans.DateChooserCombo();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(183, 161, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, 30));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 50, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Ruta", "Costo", "Ingresos", "Ganancia"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 430, 240));

        jButton2.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jButton2.setText("Exportar HTML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, -1));
        jPanel1.add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, -1));
        jPanel1.add(Fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(combo.getSelectedItem().toString().equals("Todos")){
      tabla.removeAll();
      LlenarTabla2();
      }else{
      tabla.removeAll();    
      LlenarTabla1();
      
      }
    }//GEN-LAST:event_jButton1ActionPerformed
public  String llenarHTML(){
    
      
      File file=new File("report.png");
      String scr=file.getAbsolutePath();
String HTML="<!DOCTYPE html>\n" +
"<html lang=\"en\">\n" +
"<head>\n" +
"    <meta charset=\"UTF-8\">\n" +
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
"    <title>Document</title>\n" +
"</head>\n" +
"<body>\n" +
"    <header>\n" +
"        <img  src=\""+scr+"\" alt=\"img\">\n" +
"    </header>\n" +
"     \n" +
        "<ul>\n" +
"        <div >\n" +
"            <table id=\"historial\" style=\"width: 50%\" >\n" +
"                    \n" +
"                <tr>\n" +
"                        <th><h2>ID_RUTA</h2></th>\n" +
"                        <th><h2>COSTO</h2></th>\n" +
"                        <th><h2>INGRESO</h2></th> \n" +
"                        <th><h2>GANANCIA</h2></th> \n" + 
       
"               </tr >\n" +//html+
"            </table>\n" +
"            </div>\n" +
"</ul>\n" +
        
" <style>\n" +
" body{\n" +
"     background-color: darkblue;\n" +
" }\n" +
" header{\n" +
"    background-color: white;\n" +
"\n" +
" }\n" +
" img{\n" +
"    height: 15%;\n" +
"    width: 15%;\n" +
"    padding-left: 43%;\n" +
"\n" +
" }\n" +
" th{\n" +
"background-color: white;\n" +
"margin: auto;\n" +
" }\n" +
" table{\n" +
"     background-color:steelblue;\n" +
"     margin: auto;\n" +
" }\n" +
"h4{\n" +
"text-align: center;\n" +
"\n" +
"}\n" +
"</style>   \n" +
"\n" +
""+
"</table>\n" +
"</body>\n" +
"</html>";

return HTML;
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
          Directori a=new Directori();
        
        File file=new File(a.directorio());
        if(file.exists()){
        JOptionPane.showMessageDialog(this,"Este archivo ya existe");
        }else{
           try {
               BufferedWriter bw;
               bw = new BufferedWriter(new FileWriter(file));
               bw.write( llenarHTML());
                bw.close();
           } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,"Error al guardar");
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void LlenarTabla1(){
    html="";
    Costo=0;
    Ingreso=0;
    ganancia=0;
        try {
            PreparedStatement Table;
           String fecha1="'"+Jfecha1()+"'";
           
            String fecha2="'"+Jfecha2()+"'";
            
            System.out.println(fecha1+" "+fecha2);
            Table=connection.prepareStatement("SELECT ganancia.ganancia FROM ganancia WHERE id_ruta=?"
                    + "&& fecha BETWEEN "+fecha1 +"AND"+fecha2);
            Table.setInt(1,Integer.parseInt(obtenerLetra()));
            
            ResultSet I;
            I=Table.executeQuery();
            while(I.next()){
            this.Ingreso+=I.getInt("ganancia");
            }
            Table=connection.prepareStatement("SELECT paquete.precio FROM paquete WHERE id_ruta=? && (estado=? || estado=?)"
                    + "&& fecha BETWEEN "+fecha1+"AND"+fecha2 );
            Table.setInt(1,Integer.parseInt(obtenerLetra()));
            Table.setString(2, "entregado");
            Table.setString(3,"destino");
            I=Table.executeQuery();
            while(I.next()){
            this.Costo+=I.getInt("precio");
            }
            System.out.println(Costo+" "+ganancia);
            this.ganancia=Ingreso-Costo;
            String matris[][]=new String[1][5];
            matris[0][0]=obtenerLetra();
            matris[0][1]=Integer.toString(Costo);
            matris[0][2]=Integer.toString(Ingreso);
            matris[0][3]=Integer.toString(ganancia);
              html+="<tr>"
            + "<td>"+matris[0][0]+" </td> "
            + "<td>"+matris[0][1]+" </td> "
            + "<td>"+matris[0][2]+" </td> "
            + "<td>"+matris[0][3]+" </td> "
            
                       + "</tr>";
            
            tabla.setModel(new javax.swing.table.DefaultTableModel(
          matris,
          new String [] {
                "ID Ruta", "Costo", "Ingresos", "Ganancia"
            }
        ));
     tabla.disable();
        } catch (SQLException ex) {
        System.out.println(ex.getMessage());
        }
         
    
}
public void LlenarTabla2(){
    String matris[][]=new String[COLARUTA.size()+1][4];
     Costo=0;
    Ingreso=0;
    ganancia=0;
    int Ganancia_total=0;
    int Ingreso_total=0;
    int Costo_total=0;
    html="";
    PreparedStatement Table;
     ResultSet I;
   for(int i=0;i<COLARUTA.size();i++ ){
        Costo=0;
    Ingreso=0;
    ganancia=0;
        try {
            
   
            String fecha1="'"+Jfecha1()+"'";
            String fecha2="'"+Jfecha2()+"'";
            Table=connection.prepareStatement("SELECT ganancia.ganancia FROM ganancia WHERE id_ruta=?"
                    + "&& fecha BETWEEN "+fecha1+"AND"+fecha2 );
            
            Table.setInt(1,COLARUTA.get(i).getName());
           
            I=Table.executeQuery();
            while(I.next()){
            this.Ingreso+=I.getInt("ganancia");
           
            }
            Table=connection.prepareStatement("SELECT paquete.precio FROM paquete WHERE id_ruta=? && (estado=? || estado=?)"
                    + "&& fecha BETWEEN "+fecha1+"AND"+fecha2  );
            Table.setInt(1,COLARUTA.get(i).getName());
            Table.setString(2, "entregado");
            Table.setString(3,"destino");
            
            I=Table.executeQuery();
            while(I.next()){
            this.Costo+=I.getInt("precio");
            
            }
            System.out.println(Costo+" "+ganancia);
            this.ganancia=Ingreso-Costo;
             Ganancia_total+=ganancia;
             Ingreso_total+=Ingreso;
             Costo_total+=Costo;
            matris[i][0]=Integer.toString(COLARUTA.get(i).getName());
            matris[i][1]=Integer.toString(Costo);
            matris[i][2]=Integer.toString(Ingreso);
            matris[i][3]=Integer.toString(ganancia);
          
        
    
        } catch (SQLException ex) {
        System.out.println(ex.getMessage());
        }
   }
    matris[COLARUTA.size()][0]="";
       matris[COLARUTA.size()][1]=Integer.toString(Costo_total);
       matris[COLARUTA.size()][2]=Integer.toString(Ingreso_total);
       matris[COLARUTA.size()][3]=Integer.toString(Ganancia_total);
       
   for(int i=0; i<matris.length;i++){
       html+="<tr>"
            + "<td>"+matris[i][0]+" </td> "
            + "<td>"+matris[i][1]+" </td> "
            + "<td>"+matris[i][2]+" </td> "
            + "<td>"+matris[i][3]+" </td> "
          
               
                       + "</tr>";
       
   }    
       html+="<tr>"
               + "<td>"+matris[COLARUTA.size()][0]+"/td>"
               + "<td>"+matris[COLARUTA.size()][1]+"/td>"
               + "<td>"+matris[COLARUTA.size()][2]+"/td>"
               + "<td>"+matris[COLARUTA.size()][3]+"/td>"
                +"</tr>";          
     
       tabla.setModel(new javax.swing.table.DefaultTableModel(
          matris,
          new String [] {
                "ID Ruta", "Costo", "Ingresos", "Ganancia"
            }
        ));
   
         
     tabla.disable();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo Fecha1;
    private datechooser.beans.DateChooserCombo Fecha2;
    private javax.swing.JComboBox<String> combo;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
