/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import static Inicio.IniciarConeccion.connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import static ExtraClasses.GenararPilas.COLARUTA;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.LinkedList;
import java.lang.NullPointerException;
import javax.swing.JOptionPane;
/**
 *
 * @author jhonny
 */
public class PopularPaths extends javax.swing.JInternalFrame {
LinkedList<Path> list;
String html;
    public PopularPaths() {
        initComponents();
        list=new LinkedList();
        llenarTabla();
       
    }
public  void llenarTabla(){
      html="";
      String matris[][]=new String[3][2];
      PreparedStatement Table; 
      ResultSet I;
      int count=0;
      System.out.println(COLARUTA.size());
      for(int i=0; i<COLARUTA.size();i++){
          count=0;
      try {
          
            Table=connection.prepareStatement("SELECT paquete.estado FROM paquete WHERE id_ruta=?" );
            Table.setInt(1,COLARUTA.get(i).getName());
            I=Table.executeQuery();
            while(I.next()){
                count++;
            }
          
            Path tmp=null;
            tmp=new Path(COLARUTA.get(i).getName(), count);
            list.add(tmp);
      } catch (SQLException ex) {
         System.out.println(ex.getMessage());
         }
      }
    
    int Max=0;
    int Eliminar=0;
    for(int j=0; j<3; j++){
  
    Eliminar=0;
    for(int i=0; i<list.size();i++){
    try{
    if(list.get(i).getCant()>Max){
           Eliminar=i;
           matris[j][0]=Integer.toString(list.get(i).getCod());
   matris[j][1]=Integer.toString(list.get(i).getCant());
     html+="<tr>"
            + "<td>"+matris[j][0]+" </td> "
            + "<td>"+matris[j][1]+" </td> "
          
                       + "</tr>";
       }
    }catch(NullPointerException e){
 
     }      
        
    }
    
   
    list.set(Eliminar,null);
    }  
        tabla.setModel(new javax.swing.table.DefaultTableModel(
          matris,
           new String [] {
                "ID RUTA", "#PAQUETES"
            }
        ));
     tabla.disable(); 
            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/popular.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, 130));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID RUTA", "#PAQUETES"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 450, 110));

        jButton1.setText("HTML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public  String llenarHTML(){
String HTML="<!DOCTYPE html>\n" +
"<html lang=\"en\">\n" +
"<head>\n" +
"    <meta charset=\"UTF-8\">\n" +
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
"    <title>Document</title>\n" +
"</head>\n" +
"<body>\n" +
"    <header>\n" +
"        <img  src=\"report.png\" alt=\"img\">\n" +
"    </header>\n" +
"     \n" +
        "<ul>\n" +
"        <div >\n" +
"            <table id=\"historial\" style=\"width: 50%\" >\n" +
"                    \n" +
"                <tr>\n" +
"                        <th><h2>ID_RUTA</h2></th>\n" +
"                        <th><h2>PAQUETES</h2></th>\n" +
     
"               </tr >\n" +html+
"            </table>\n" +
"            </div>\n" +
"</ul>\n" +
        
" <style>\n" +
" body{\n" +
"     background-color: darkblue;\n" +
" }\n" +
" header{\n" +
"    background-color: white;\n" +
"\n" +
" }\n" +
" img{\n" +
"    height: 15%;\n" +
"    width: 15%;\n" +
"    padding-left: 43%;\n" +
"\n" +
" }\n" +
" th{\n" +
"background-color: white;\n" +
"margin: auto;\n" +
" }\n" +
" table{\n" +
"     background-color:steelblue;\n" +
"     margin: auto;\n" +
" }\n" +
"h4{\n" +
"text-align: center;\n" +
"\n" +
"}\n" +
"</style>   \n" +
"\n" +
""+
"</table>\n" +
"</body>\n" +
"</html>";

return HTML;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  Directori a=new Directori();
        
        File file=new File(a.directorio());
        if(file.exists()){
        JOptionPane.showMessageDialog(this,"Este archivo ya existe");
        }else{
           try {
               BufferedWriter bw;
               bw = new BufferedWriter(new FileWriter(file));
               bw.write( llenarHTML());
                bw.close();
           } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,"Error al guardar");
           }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
