/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import static Inicio.IniciarConeccion.connection;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;

import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class Rutas extends javax.swing.JInternalFrame {
 String html;
 String HTML;
 
    public Rutas() {
        initComponents();
        this.html="";
        this.HTML="";
       
        combo.removeAllItems();
        combo.addItem("activo");
        combo.addItem("desactivado");
       
    }
public final void llenarHTML(){
      
      File file=new File("report.png");
      String scr=file.getAbsolutePath();
this.HTML="<!DOCTYPE html>\n" +
"<html lang=\"en\">\n" +
"<head>\n" +
"    <meta charset=\"UTF-8\">\n" +
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n" +
"    <title>Document</title>\n" +
"</head>\n" +
"<body>\n" +
"    <header>\n" +
"        <img  src=\""+scr+"\" alt=\"img\">\n" +
"    </header>\n" +
"     \n" +
        "<ul>\n" +
"        <div >\n" +
"            <table id=\"historial\" style=\"width: 50%\" >\n" +
"                    \n" +
"                <tr>\n" +
"                        <th><h2>ID RUTA</h2></th>\n" +
"                        <th><h2>EN RUTA</h2></th>\n" +
"                        <th><h2>ENTREGADO</h2></th> \n" +
"               </tr >\n" +html+
"            </table>\n" +
"            </div>\n" +
"</ul>\n" +
        
" <style>\n" +
" body{\n" +
"     background-color: darkblue;\n" +
" }\n" +
" header{\n" +
"    background-color: white;\n" +
"\n" +
" }\n" +
" img{\n" +
"    height: 15%;\n" +
"    width: 15%;\n" +
"    padding-left: 43%;\n" +
"\n" +
" }\n" +
" th{\n" +
"background-color: white;\n" +
"margin: auto;\n" +
" }\n" +
" table{\n" +
"     background-color:steelblue;\n" +
"     margin: auto;\n" +
" }\n" +
"h4{\n" +
"text-align: center;\n" +
"\n" +
"}\n" +
"</style>   \n" +
"\n" +
""+
"</table>\n" +
"</body>\n" +
"</html>";
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(188, 182, 175));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        jButton1.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ruta", "En ruta", "fuera de ruta"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 190));

        jButton2.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jButton2.setText("Exportar HTML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
    LinkedList<Integer> ID=new LinkedList();          
    PreparedStatement select =connection.prepareStatement("SELECT ruta.id_ruta FROM ruta WHERE estado=?");
    select.setString(1,combo.getSelectedItem().toString());
    ResultSet res=select.executeQuery();
    while(res.next()){
        ID.add(res.getInt("id_ruta"));
    }
    OrganizarDatos(ID);
    
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      llenarHTML();
        Directori a=new Directori();
        
        File file=new File(a.directorio());
        if(file.exists()){
        JOptionPane.showMessageDialog(this,"Este archivo ya existe");
        }else{
           try {
               BufferedWriter bw;
               bw = new BufferedWriter(new FileWriter(file));
               bw.write(HTML);
                bw.close();
           } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,"Error al guardar");
           }
        }
     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     *
     * @param path
     * @return 
     */
    @SuppressWarnings("empty-statement")


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void OrganizarDatos(LinkedList<Integer> ID) {
    LinkedList<Ruta> ruta=new LinkedList();    
    for(int i=0;i<ID.size();i++){
     try {
    PreparedStatement select =connection.prepareStatement("SELECT paquete.estado FROM paquete WHERE id_ruta=?");
    select.setInt(1, ID.get(i));
    ResultSet res=select.executeQuery();
    int EnRuta=0;
    int Entregado=0;
    while(res.next()){
        String tmp=res.getString("estado");
        if(tmp.equals("by way")){
        EnRuta++;    
        }else{
        Entregado++;
        }
    }
    Ruta tmp=new Ruta(EnRuta,Entregado);
    ruta.add(tmp);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    String matris[][]=new String[ID.size()][3];
   
    for(int i=0;i<ID.size();i++){
        
    matris[i][0]=Integer.toString(ID.get(i));
    matris[i][1]=Integer.toString(ruta.get(i).getEnRuta());
    matris[i][2]=Integer.toString(ruta.get(i).getEntregado());
    html+="<tr>"
            + "<td>"+matris[i][0]+" </td> "
            + "<td>"+matris[i][1]+" </td> "
            + "<td>"+matris[i][2]+" </td> "
            + "</tr>";
     
        
    }
    
     tabla.setModel(new javax.swing.table.DefaultTableModel(
          matris,
          new String [] {
                "Id ruta", "En ruta", "fuera de ruta"
            }
        ));
     tabla.disable();
    }
}
