/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recepcionista;

import static Inicio.IniciarConeccion.connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.lang.NullPointerException;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class Lookforpackage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Lookforpackage
     */
    public Lookforpackage() {
        initComponents();
        this.setLocation(50, 50);
        text.setText("Waiting...");
        Pcod.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cui = new javax.swing.JTextField();
        text = new javax.swing.JLabel();
        Pcod = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 42, 31));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(216, 247, 119));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 193, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        jLabel1.setText("Codigo de paquete");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 60));

        cui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuiKeyTyped(evt);
            }
        });
        jPanel2.add(cui, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));

        text.setFont(new java.awt.Font("Ubuntu Mono", 1, 16)); // NOI18N
        text.setText("               WAITING...");
        jPanel2.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 390, 50));

        Pcod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Pcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcodActionPerformed(evt);
            }
        });
        jPanel2.add(Pcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public  int tmp;
    private void cuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuiKeyTyped
                char validar=evt.getKeyChar();
          if(Character.isLetter(validar)  ){   
        getToolkit().beep();
        evt.consume();
        }

    }//GEN-LAST:event_cuiKeyTyped

    private void PcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcodActionPerformed
    
        try {
            PreparedStatement declaracion =connection.prepareStatement("SELECT paquete.id_pc FROM paquete WHERE id_paquete=?");
            declaracion.setInt(1, Integer.parseInt(Pcod.getSelectedItem().toString()));
            tmp=0;
            ResultSet res=declaracion.executeQuery();
            while(res.next()){
            tmp=res.getInt("id_pc");
          
            }
            boolean VD=true;
            if(tmp==0){
            text.setText("El paquete esta en la bodega ");
            VD=false;
            }else if(tmp==-1){
            text.setText("El paquete esta en el destino ");
            VD=false;
            }else if(VD){
            text.setText("El paquete esta en el punto de control "+tmp);
            }
            
            
        } catch (SQLException ex) {
        System.out.println(ex.getMessage());
        } catch(NullPointerException exs){
        
        }
   

    }//GEN-LAST:event_PcodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pcod.removeAllItems();
        try {
         PreparedStatement declaracion =connection.prepareStatement("SELECT paquete.id_paquete FROM paquete WHERE  cui=?" );
         declaracion.setInt(1, Integer.parseInt(cui.getText()));
         ResultSet re=declaracion.executeQuery();
         while(re.next()){
         Pcod.addItem(Integer.toString(re.getInt("id_paquete")));
         }
         
         
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Cliente no valido");
        System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Pcod;
    private javax.swing.JTextField cui;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
