/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recepcionista;

import static Inicio.IniciarConeccion.connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class Lookforpackage extends javax.swing.JInternalFrame {

    /**
     * Creates new form Lookforpackage
     */
    public Lookforpackage() {
        initComponents();
        this.setLocation(50, 50);
        text.setText("Waiting...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        text = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 42, 31));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(216, 247, 119));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(61, 193, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        jLabel1.setText("Codigo de paquete");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 60));

        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });
        jPanel2.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));

        text.setFont(new java.awt.Font("Ubuntu Mono", 1, 16)); // NOI18N
        text.setText("               WAITING...");
        jPanel2.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 390, 50));

        jButton1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public  int tmp;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   boolean validar=true;
        try {
            PreparedStatement declaracion =connection.prepareStatement("SELECT paquete.id_pc FROM paquete WHERE id_paquete=?");
            declaracion.setInt(1, Integer.parseInt(codigo.getText()));
            tmp=0;
            ResultSet res=declaracion.executeQuery();
            while(res.next()){
            tmp=res.getInt("id_pc");
            validar=false;
            }
            if(tmp==0){
            text.setText("El paquete esta en la bodega ");
            }else if(tmp==-1){
            text.setText("El paquete esta en el destino ");
            }else if(!(tmp==0 && tmp==-1)){
            text.setText("El paquete esta en el punto de control "+tmp);
            }
            
            
        } catch (SQLException ex) {
        System.out.println(ex.getMessage());
        }
    if(validar){
        JOptionPane.showMessageDialog(this, "Codigo de paquete no valido");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
                char validar=evt.getKeyChar();
          if(Character.isLetter(validar)  ){   
        getToolkit().beep();
        evt.consume();
        }

    }//GEN-LAST:event_codigoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
