package Recepcionista;
import ExtraClasses.Cola;
import static ExtraClasses.GenararPilas.COLARUTA;
import ExtraClasses.Paquete;
import static Inicio.IniciarConeccion.connection;
import Inicio.Welcome;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import ExtraClasses.GenararPilas;
import java.sql.Date;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Recepcionist extends javax.swing.JFrame {
    DefaultTableModel model;
     
    Object[] o=new Object[3];
    public LinkedList <Paquete> Package=null;
    public int costo;
    public Recepcionist() {
        initComponents();
        this.setLocationRelativeTo(this);
        Package=new LinkedList();
        llenarCombo();
        model=(DefaultTableModel)tabla.getModel();
        this.costo=0;
     
    }
    public void llenarCombo(){
   combo.removeAllItems();
        try {
        declaracion =connection.prepareStatement("SELECT ruta.direccion_rta, ruta.id_ruta FROM ruta WHERE estado=? " );
        declaracion.setString(1, "activo");
        ResultSet re=declaracion.executeQuery();
         while(re.next()){
         combo.addItem(re.getString("direccion_rta")+" "+"ID:"+re.getString("id_ruta"));
         }
         
         
        } catch (SQLException ex) {
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kind = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cui = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(38, 54, 228));

        jPanel3.setBackground(new java.awt.Color(166, 152, 243));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jPanel4.setBackground(new java.awt.Color(177, 187, 198));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recepcionist.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Check.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 110, 510));

        jLabel3.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jLabel3.setText("Direccion de destino");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jLabel4.setText("Tipo de prioridad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        kind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin prioridad", "Prioridad" }));
        jPanel1.add(kind, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 130, -1));

        jLabel5.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jLabel5.setText("Peso de paquete");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoKeyTyped(evt);
            }
        });
        jPanel1.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 130, -1));

        send.setFont(new java.awt.Font("Umpush", 1, 14)); // NOI18N
        send.setText("Enviar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Uroob", 1, 18)); // NOI18N
        jLabel6.setText("CUI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        cui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuiActionPerformed(evt);
            }
        });
        cui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuiKeyTyped(evt);
            }
        });
        jPanel1.add(cui, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 130, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 130, -1));

        add.setText("Agregar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paquete", "Peso", "Destino"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 370, 170));

        Total.setText("0");
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 50, 30));

        jLabel2.setText("Total");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 448, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
   CreateClient a =new CreateClient();
   a.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuiKeyTyped
        // TODO add your handling code here:
       
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar) ){   
        getToolkit().beep();
        evt.consume();
        }
        
           if(cui.getText().length()>9){
        getToolkit().beep();
        evt.consume();
        
           }
        
    }//GEN-LAST:event_cuiKeyTyped

    private void pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoKeyTyped
        // TODO add your handling code here:
           char validar=evt.getKeyChar();
        
           if(Character.isLetter(validar) ){   
        getToolkit().beep();
        evt.consume();
        }
        
           if(peso.getText().length()>10){
        getToolkit().beep();
        evt.consume();
        
           }
        
    }//GEN-LAST:event_pesoKeyTyped
public boolean validarCliente;
    public boolean validar(){
if(cui.getText().equals("") || peso.getText().equals("") )
    return false;
else return true;
}
public void validarCliente(){
    validarCliente=false;
boolean valid=true;
        try {
            PreparedStatement declaracion =connection.prepareStatement("SELECT cliente.cui FROM cliente WHERE cui=?");
            int tmp=Integer.parseInt(cui.getText());
            declaracion.setInt(1,tmp);
             ResultSet re=declaracion.executeQuery();
           while(re.next()){
           if(tmp==re.getInt("cui")){
           JOptionPane.showMessageDialog(this,"Cliente valido");
            valid=false;
            validarCliente=true;
           }
           }
        } catch (SQLException ex) {
        System.out.println(ex.getMessage());
        }
if(valid){
JOptionPane.showMessageDialog(this,"Este cliente no existe");
}    
    
    
}


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Welcome open =new Welcome();
        open.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_pesoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Packages open =new Packages();
        open.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    public void Send(){
        int cod=0;
       for(int i=0; i<COLARUTA.size();i++){
        if(Integer.parseInt(obtenerLetra())==COLARUTA.get(i).getName()){
            cod=i;
            break;
        }
        
    }
       try{
            LinkedList<Cola> c=COLARUTA.get(cod).getA();
            
           
            for(int i=0;i<Package.size();i++){
            if(c.get(0).isFull()){
            
            }else{
            c.get(0).push(Package.get(i));
            ActualizarBase(c);
            }
            
            }
 
       }catch(IndexOutOfBoundsException e){
       
       }
       
    }
    
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        generarFactura();
        cui.enable();
        peso.setText("");
        cui.setText("");
        Total.setText("");
        int a=tabla.getRowCount()-1;
        for(int i=a; i>=0;i--){
        
        }
        model.setRowCount(0);
       
    }//GEN-LAST:event_sendActionPerformed
public PreparedStatement declaracion=null;
    
   
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    
        if(validar()){
            if(cui.isEnabled()){
            validarCliente();
            }
            cui.disable();
            if(validarCliente){
                try{
                
                
            crearPaquete();
            Paquete tmp;
            tmp=new Paquete(0,Integer.parseInt(peso.getText()),Integer.parseInt(obtenerLetra()),"by way",
            costo,kind.getSelectedItem().toString(),Integer.parseInt(cui.getText()),0);
            Package.add(tmp);
            Send();
           GenararPilas a=new GenararPilas();
            a.GeneratePilas();
            }catch(NumberFormatException e){
                
                }
            }
            }   
    }//GEN-LAST:event_addActionPerformed

   
public void crearPaquete(){
  
    
    try {
          PreparedStatement declaracion =connection.prepareStatement("INSERT INTO paquete(peso, id_ruta, estado, precio,prioridad"
          + ",cui, id_pc,fecha) VALUES (?, ?, ?, ?,?,?,?,?)");
        
           
          declaracion.setInt(1,Integer.parseInt(peso.getText()));
          declaracion.setInt(2,Integer.parseInt(obtenerLetra()) );
          declaracion.setString(3, "by way");
           
          declaracion.setInt(4, 0);
          declaracion.setString(5, kind.getSelectedItem().toString());
          declaracion.setInt(6, Integer.parseInt(cui.getText()));
          declaracion.setInt(7, 0);
           java.util.Date fecha = new java.util.Date();
            Date d;
            d = new Date(fecha.getYear(),fecha.getMonth(),fecha.getDay());
            declaracion.setDate(8,d);
          declaracion.executeUpdate();
            o[0]=kind.getSelectedItem().toString();
            o[1]=peso.getText();
            o[2]=combo.getSelectedItem().toString();
            model.addRow(o);
          GenerarGanancia();
        } catch (SQLException ex   ) {
       System.out.println(ex.getMessage());
        } catch(NumberFormatException e){
        
        }
}
    private void cuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuiActionPerformed
        
        
        
    }//GEN-LAST:event_cuiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PickUpPackage a=new PickUpPackage();
        a.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public void GenerarGanancia(){
        try {
            PreparedStatement tmp;
            this.costo=0;
            int cod=0;
            tmp=connection.prepareStatement("SELECT paquete.id_paquete FROM paquete order by id_paquete desc limit 1 ");
            ResultSet resultado=tmp.executeQuery();
            while(resultado.next()){
                cod=resultado.getInt("id_paquete");
            }
            PreparedStatement precio =connection.prepareStatement("SELECT ruta.precio_rta FROM ruta WHERE id_ruta=?");
            precio.setInt(1, Integer.parseInt(obtenerLetra()) );
            ResultSet res=precio.executeQuery();
            while(res.next()){
                this.costo=res.getInt("precio_rta");
            }
            
            PreparedStatement G =connection.prepareStatement("SELECT datos.precioLibra FROM datos ");
            precio.setInt(1, Integer.parseInt(obtenerLetra()) );
            ResultSet Gs=G.executeQuery();
            while(Gs.next()){
                this.costo+=((Integer.parseInt(peso.getText()))*(Gs.getInt("precioLibra")));
            }
            
            
            PreparedStatement ganancia =connection.prepareStatement("INSERT INTO ganancia(id_ruta,id_paquete, cui, ganancia, fecha) VALUES (?,?,?,?,?)");
            
            ganancia.setInt(1, Integer.parseInt(obtenerLetra()) );
            ganancia.setInt(2, cod);
            ganancia.setInt(3, Integer.parseInt(cui.getText()));
            ganancia.setInt(4,this.costo );
             java.util.Date fecha = new java.util.Date();
            Date d;
            d = new Date(fecha.getYear(),fecha.getMonth(),fecha.getDay());
            ganancia.setDate(5,d);
            ganancia.executeUpdate();
            int total=Integer.parseInt(Total.getText())+costo;
        Total.setText(Integer.toString(total));
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
          

}
 public void generarFactura(){
    
 }   
  public String obtenerLetra(){
    String letra="";
      try{
     String tmp=combo.getSelectedItem().toString();
     String [] vect=tmp.split("");
     String numbers="1234567890";
     String [] vect2=numbers.split("");
     
     for(int i=0; i<tmp.length();i++){
       
     for(int j=0;j<numbers.length();j++){
         
     if(vect[i].equals(vect2[j]))
     {
        letra+=vect[i]; 
     
     break;
     }
     }
     }
    }catch(NullPointerException e){
     
     }   
    return letra;}   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField cui;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kind;
    private javax.swing.JTextField peso;
    private javax.swing.JButton send;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    public void ActualizarBase(LinkedList<Cola> c) {
       
        int cod=0;
      try {
           PreparedStatement tmp;
            tmp=connection.prepareStatement("SELECT paquete.id_paquete FROM paquete order by id_paquete desc limit 1 ");
            ResultSet res=tmp.executeQuery();
            while(res.next()){
            cod=res.getInt("id_paquete");
            }
                
        } catch (SQLException ex) {
       System.out.println(ex.getMessage()+"1");
       
        }
        
        
      try {
            declaracion=connection.prepareStatement("UPDATE paquete SET id_pc=? WHERE id_paquete=?");
            declaracion.setInt(1,c.get(0).getId());
            declaracion.setInt(2, cod);
            declaracion.executeUpdate();
                
        } catch (SQLException ex) {
       
       System.out.println(ex.getMessage()+"2");
       
        }
    }
}
